name: ITM 350 Build Pipeline

on:
    workflow_dispatch: 
    push:
        branches: 
            -main

jobs:
    BuildPipeline:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World"

            - name: Checkout Repository  
              uses: actions/checkout@v3
            
            - name: Log into Docker Hub
              run: echo "${{ secrets.DOCKER_LEVI_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LEVI_USERNAME }}" --password-stdin
            - name: Build Docker Image
              run: |
               docker build -t  ${{ secrets.DOCKER_LEVI_USERNAME }}/ghost:latest . 
               docker push ${{ secrets.DOCKER_LEVI_USERNAME }}/ghost:latest

            - name: Log into Docker Hub
              run: echo "${{ secrets.DOCKER_HAYDEN_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HAYDEN_USERNAME }}" --password-stdin
            - name: Build Docker Image
              run: |
               docker build -t  ${{ secrets.DOCKER_HAYDEN_USERNAME }}/ghost:latest . 
               docker push ${{ secrets.DOCKER_HAYDEN_USERNAME }}/ghost:latest

            - name: Log into Docker Hub
              run: echo "${{ secrets.DOCKER_EMA_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LEVI_USERNAME }}" --password-stdin
            - name: Build Docker Image
              run: |
               docker build -t  ${{ secrets.DOCKER_EMA_USERNAME }}/ghost:latest . 
               docker push ${{ secrets.DOCKER_EMA_USERNAME }}/ghost:latest
