name: ITM 350 Release Pipeline

on:
    workflow_dispatch: 

jobs:
    BuildPipeline:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World"

            - name: Checkout Repository  
              uses: actions/checkout@v3
            
            # This will create a docker image on EACH of our personal docker hubs. :)
            - name: Log into Docker Hub
              run: echo "${{ secrets.DOCKER_LEVI_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LEVI_USERNAME }}" --password-stdin
            - name: Build Docker Image
              run: |
               docker build -t  ${{ secrets.DOCKER_LEVI_USERNAME }}/ghost:latest . 
               docker push ${{ secrets.DOCKER_LEVI_USERNAME }}/ghost:latest

            - name: Log into Docker Hub
              run: echo "${{ secrets.DOCKER_HAYDEN_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HAYDEN_USERNAME }}" --password-stdin
            - name: Build Docker Image
              run: |
               docker build -t  ${{ secrets.DOCKER_HAYDEN_USERNAME }}/ghost:latest . 
               docker push ${{ secrets.DOCKER_HAYDEN_USERNAME }}/ghost:latest

            - name: Log into Docker Hub
              run: echo "${{ secrets.DOCKER_EMA_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_EMA_USERNAME }}" --password-stdin
            - name: Build Docker Image
              run: |
               docker build -t  ${{ secrets.DOCKER_EMA_USERNAME }}/ghost:latest . 
               docker push ${{ secrets.DOCKER_EMA_USERNAME }}/ghost:latest

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: latest

            - name: Terraform Init
              run: 
                cd ..\..\iac
                terraform init
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Terraform Plan
              run: terraform plan
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}